# Generated by Django 4.2.3 on 2023-08-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('vegetation_app', '0001_initial'), ('vegetation_app', '0002_rename_water_frequency_plant_water_frequency_summer_and_more'), ('vegetation_app', '0003_rename_water_tolerance_plant_drought_tolerance')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('last_watered', models.DateTimeField()),
                ('water_frequency_summer', models.IntegerField()),
                ('light_requirement', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('water_frequency_winter', models.IntegerField(default=3)),
                ('drought_tolerance', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('watering_type', models.CharField(choices=[('SP', 'Sprinkler'), ('SA', 'Saucer'), ('PL', 'Planter')], default='SP', max_length=2)),
            ],
        ),
    ]
